# Generated by Django 3.2.6 on 2021-08-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatroom_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
