# Generated by Django 3.2.6 on 2021-08-06 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_chatroom_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='room_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
